export const ERROR_CODES = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  CHECKOUT_LINK_NOT_FOUND_OR_INACTIVE: 'CHECKOUT_LINK_NOT_FOUND_OR_INACTIVE',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  INVALID_CHECKOUT_INPUT: 'INVALID_CHECKOUT_INPUT',
  INVALID_ORDER_STATUS_TRANSITION: 'INVALID_ORDER_STATUS_TRANSITION',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
