export const ERROR_CODES = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  CHECKOUT_LINK_NOT_FOUND_OR_INACTIVE: 'CHECKOUT_LINK_NOT_FOUND_OR_INACTIVE',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  INVALID_CHECKOUT_INPUT: 'INVALID_CHECKOUT_INPUT',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
